SPACE:
  NAME: 'darts'
  NUM_CLASSES: 10
SEARCH:
  DATASET: 'cifar10'
  SPLIT: [0.8, 0.2]
  BATCH_SIZE: 256
  IM_SIZE: 32
OPTIM:
  STEPS: [48, 96]
  BASE_LR: 0.025
  LR_POLICY: 'step'
SNG:
  NAME: 'DDPNAS'
  THETA_LR: 0.0001
  PRUNING: True
  PROB_SAMPLING: False
  MOMENTUM: True
  GAMMA: 0.9
DATA_LOADER:
  BACKEND: 'custom'
OUT_DIR: '/userhome/project/XNAS/experiment/DDPNAS_test'
